### ISSUE TITLE
Is there a way to add some visitor counter function into it?

### ISSUE THREAD

**Issue by kenshinji** [t413/SinglePaged#28]

**Comment by blairanderson** [comment]
@kenshinji you can use any visitor counter you want, cannot be built in because it depends on your domain name

**Comment by t413** [comment]
Not directly since github pages are static and can't change their content on demand. This increases security, reduces complexity, and makes things cheap and fast. Instead you can use a javascript visitor counter similar to how google-analytics works. Just search google for 'simple visitor counter' and try a few.
